import pyautogui 
import PIL       
import time

# top-left pyautogui.moveTo(770,690)
# mid-left pyautogui.moveTo(770,810)
# bot-left pyautogui.moveTo(770,930)

# one pyautogui.moveTo(900,930)
# two pyautogui.moveTo(1020,930)
# the pyautogui.moveTo(1150,930)

duration = 0.2
duration2= 0.17
duration3= 0.15

#def for shapes
def SmlSqr():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.moveTo(900,810,duration=duration2)
    pyautogui.moveTo(772,810,duration=duration2)
    pyautogui.moveTo(772,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def dlSmlTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.moveTo(772,810,duration=duration2)
    pyautogui.moveTo(772,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def drSmlTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.moveTo(900,810,duration=duration2)
    pyautogui.moveTo(772,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def trSmlTri():
    pyautogui.moveTo(900,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,810,duration=duration2)
    pyautogui.moveTo(772,810,duration=duration2)
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def tlSmlTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,810,duration=duration2)
    pyautogui.moveTo(772,810,duration=duration2)
    pyautogui.moveTo(772,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def dluLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def druLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def truLngTri():
    pyautogui.moveTo(900,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration3)
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def tluLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration3)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def dlsLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def drsLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration3)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def trsLngTri():
    pyautogui.moveTo(1020,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,810,duration=duration3)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def tlsLngTri():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration3)
    pyautogui.mouseUp()
    time.sleep(1)
def twLeRec():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration2)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration2)
    pyautogui.mouseUp()
    time.sleep(1)
def twDwRec():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration2)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration2)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def thLeRec():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1150,935,duration=duration)
    pyautogui.moveTo(1150,810,duration=duration3)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration3)
    pyautogui.mouseUp()
    time.sleep(1)
def BigSqr():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def dlL():
    pyautogui.moveTo(772,935)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def drL():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def trL():
    pyautogui.moveTo(900,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def tlL():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)
def dwnT():
    pyautogui.moveTo(770,810)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(1150,810,duration=duration)
    pyautogui.moveTo(1150,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.mouseUp()        
    time.sleep(1)
def upT():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1150,935,duration=duration)
    pyautogui.moveTo(1150,810,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(772,810,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()    
    time.sleep(1)
def dwU():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(1150,935,duration=duration)
    pyautogui.moveTo(1150,690,duration=duration)
    pyautogui.moveTo(1020,690,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(900,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()    
    time.sleep(1)
def upU():
    pyautogui.moveTo(770,930)
    pyautogui.mouseDown()
    pyautogui.moveTo(900,935,duration=duration)
    pyautogui.moveTo(900,810,duration=duration)
    pyautogui.moveTo(1020,810,duration=duration)
    pyautogui.moveTo(1020,935,duration=duration)
    pyautogui.moveTo(1150,935,duration=duration)
    pyautogui.moveTo(1150,690,duration=duration)
    pyautogui.moveTo(772,690,duration=duration)
    pyautogui.moveTo(772,935,duration=duration)
    pyautogui.mouseUp()
    time.sleep(1)


def run():
    
    pyautogui.MINIMUM_DURATION = 0.1
    pyautogui.PAUSE = 0.1

    Layout = ["Trace_Cadets_A","Trace_Cadets_B","Trace_Cadets_C","Trace_Cadets_D","Trace_Cadets_E"]
    index=0
    drawing=False

    i=0
    while (i<10):
        pyautogui.keyDown("l")
        pyautogui.keyUp("l")
        i=i+1

    time.sleep(2.5)

    while(drawing == False):
        try:
            pyautogui.locateOnScreen(f'{Layout[index]}.PNG', confidence=.8)
            drawing = True
        except Exception as e:
            print(f'{Layout[index]}.PNG')
            index=index+1
            if (index==5):
                index=0
    time.sleep(3)
    
    if(index==0):
        drL()
        twDwRec()
        BigSqr()
        SmlSqr()
        dwnT()
        SmlSqr()
        BigSqr()
        SmlSqr()
        tlL()
        tlSmlTri()
        drSmlTri()
    if(index==1):
        twLeRec()
        twLeRec()
        twDwRec()
        BigSqr()
        SmlSqr()
        twDwRec()
        tluLngTri()
        druLngTri()
        SmlSqr()
        drL()
        twLeRec()
        drL()
    if(index==2):
        upU()
        twDwRec()
        SmlSqr()
        tlsLngTri()
        drsLngTri()
        dlL()
        twDwRec()
        twLeRec()
        upT()
        SmlSqr()
        twLeRec()
    if(index==3):
        SmlSqr()
        thLeRec()
        truLngTri()
        dluLngTri()
        thLeRec()
        dlsLngTri()
        trsLngTri()
        drL()
        dlL()
        twLeRec()
        drL()
        twDwRec()
    if(index==4):
        upT()
        twLeRec()
        SmlSqr()
        BigSqr()
        thLeRec()
        dwU()
        tlSmlTri()
        drSmlTri()
        dlL()
        dlSmlTri()
        trSmlTri()
